### ISSUE TITLE
条件付き確率

### ISSUE THREAD

**Issue by himkt** [KlisMathClub/zatsu#1]
<img width="171" alt="screen shot 2015-07-08 at 10 35 24 pm" src="https://cloud.githubusercontent.com/assets/5164000/8571491/281ade7e-25c2-11e5-9011-df3389e98310.png">

この変形の過程を教えていただけませんか..
P(x_2|x_3)を一つの確率とみなして確率全体を同時確率とみなして展開してみたら条件付き確率がおかしなことになって詰まっています

<img width="195" alt="screen shot 2015-07-08 at 10 42 37 pm" src="https://cloud.githubusercontent.com/assets/5164000/8571582/a7ec291e-25c2-11e5-9e98-a9cdb4722c00.png">

**Comment by Yousack** [comment]
p(x,y) = p(x|y)p(y)

**Comment by Yousack** [comment]
はもう分かってるのか（すみません）

**Comment by Yousack** [comment]
明確な答えにはなってないけど P(x1,x2) = P(x1|x2)P(x2) の両辺の確率を全部x3で条件づけると P(x1,x2|x3) = P(x1|x2,x3)P(x2|3) になるね（P(x1|x2,x3)はx2とx3で条件付けたx1の確率なので）

**Comment by himkt** [comment]
あーーーーなるほど、その通りですね.
ありがとうございますm(__)m

**Comment by nzw0301** [comment]
自分なりに式変形で求めたらこんな感じになりました．

![2015-07-09 1 03 16](https://cloud.githubusercontent.com/assets/7121753/8575326/69005f68-25d6-11e5-9b09-a814fa0830c3.png)

**Comment by Yousack** [comment]
LGTM

[![LGTM](http://lgtm.in/p/oUs4txf3q)](http://lgtm.in/i/oUs4txf3q)

**Comment by nzw0301** [comment]
:+1:

**Comment by cocuh** [comment]
:+1:

**Comment by himkt** [comment]
なるほど〜〜〜！！！！！！！！

**Comment by himkt** [comment]
:+1:
